/* Road Horizon — static GitHub Pages PWA */
const BORDON = [51.1132, -0.8611];
const BOUNDS = { south: 51.075, west: -0.925, north: 51.155, east: -0.795 };
const STORE = { completed: 'rh.completedRoads', journeys: 'rh.journeys', roads: 'rh.bordonRoads.v2', mode: 'rh.mode' };
const state = { map:null, roadLayer:null, roads:[], roadLayers:new Map(), completed:new Set(readJSON(STORE.completed,[])), journeys:readJSON(STORE.journeys,[]), userMarker:null, accuracyCircle:null, watchId:null, locationWatchId:null, tracking:false, lastPoint:null, distanceKm:0, pointCount:0, newRoads:new Set(), mode:localStorage.getItem(STORE.mode)||'car', hasCentred:false };

function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function $(id){return document.getElementById(id)}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function distance(a,b){const r=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function pointSegmentDistance(p,a,b){const latScale=111320,lngScale=111320*Math.cos(p.lat*Math.PI/180);const px=(p.lng-a[1])*lngScale,py=(p.lat-a[0])*latScale,bx=(b[1]-a[1])*lngScale,by=(b[0]-a[0])*latScale;const len=bx*bx+by*by;const t=len?Math.max(0,Math.min(1,(px*bx+py*by)/len)):0;return Math.hypot(px-t*bx,py-t*by)}
function roadDistance(p,coords){let best=Infinity;for(let i=1;i<coords.length;i++)best=Math.min(best,pointSegmentDistance(p,coords[i-1],coords[i]));return best}
function nearestRoad(p){let match=null,best=Infinity;for(const road of state.roads){const d=roadDistance(p,road.coords);if(d<best){best=d;match=road}}return best<=Math.max(28,p.accuracy*1.35)?{road:match,distance:best}:null}
function roadStyle(road){const done=state.completed.has(String(road.id));return {color:done?'#43df8d':'#536b62',weight:done?5:3,opacity:done?.95:.5,lineCap:'round'}}

function initMap(){state.map=L.map('map',{zoomControl:true,preferCanvas:true}).setView(BORDON,14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map);state.roadLayer=L.layerGroup().addTo(state.map);loadRoads();startLocationWatch()}
async function loadRoads(){const cached=readJSON(STORE.roads,null);if(cached?.length){setRoads(cached);$('map-status').textContent='Bordon roads loaded';return} $('map-status').textContent='Loading Bordon road network…';try{const q=`[out:json][timeout:25];way[highway][highway!~"footway|path|cycleway|steps|pedestrian|track|construction"](${BOUNDS.south},${BOUNDS.west},${BOUNDS.north},${BOUNDS.east});out geom;`;const url='https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q);const response=await fetch(url);if(!response.ok)throw new Error('Road service unavailable');const data=await response.json();const roads=data.elements.filter(x=>x.type==='way'&&x.geometry?.length>1).map(x=>({id:x.id,name:x.tags?.name||x.tags?.ref||'Unnamed road',coords:x.geometry.map(p=>[p.lat,p.lon])}));if(!roads.length)throw new Error('No roads returned');save(STORE.roads,roads);setRoads(roads);$('map-status').textContent='Bordon roads loaded'}catch(error){$('map-status').textContent='Base map ready · road overlay unavailable';toast('Road overlay needs an internet connection. Try again later.')}}
function setRoads(roads){state.roads=roads;state.roadLayer.clearLayers();state.roadLayers.clear();for(const road of roads){const layer=L.polyline(road.coords,roadStyle(road)).bindTooltip(road.name,{sticky:true});layer.addTo(state.roadLayer);state.roadLayers.set(String(road.id),layer)}updateProgress()}
function updateLocation(pos){const p={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy,time:pos.timestamp};const latlng=[p.lat,p.lng];if(!state.userMarker){state.userMarker=L.marker(latlng,{icon:L.divIcon({className:'',html:'<div class="user-location"></div>',iconSize:[18,18],iconAnchor:[9,9]}),zIndexOffset:1000}).addTo(state.map);state.accuracyCircle=L.circle(latlng,{radius:p.accuracy,color:'#1688ff',weight:1,fillColor:'#1688ff',fillOpacity:.12}).addTo(state.map)}else{state.userMarker.setLatLng(latlng);state.accuracyCircle.setLatLng(latlng).setRadius(p.accuracy)}if(!state.hasCentred){state.map.setView(latlng,16);state.hasCentred=true}$('gps-pill').textContent='GPS live';$('gps-pill').classList.add('live');$('map-accuracy').textContent=`±${Math.round(p.accuracy)} m`;$('drive-accuracy').textContent=`±${Math.round(p.accuracy)} m`;$('map-status').textContent='Showing your live location';if(state.tracking)processTrackPoint(p)}
function locationError(error){$('gps-pill').textContent='GPS unavailable';$('gps-pill').classList.remove('live');const message=error.code===1?'Location permission is needed to show you on the map.':'Could not get your location. Check GPS and try again.';toast(message)}
function startLocationWatch(){if(!navigator.geolocation){locationError({code:0});return}if(state.locationWatchId!==null)return;state.locationWatchId=navigator.geolocation.watchPosition(updateLocation,locationError,{enableHighAccuracy:true,maximumAge:3000,timeout:15000})}
function processTrackPoint(p){state.pointCount++;if(state.lastPoint){const delta=distance(state.lastPoint,p);if(delta<.5&&p.accuracy<100)state.distanceKm+=delta}state.lastPoint=p;const match=nearestRoad(p);if(match){$('matched-road').textContent=match.road.name;const id=String(match.road.id);if(!state.completed.has(id)){state.completed.add(id);state.newRoads.add(id);save(STORE.completed,[...state.completed]);state.roadLayers.get(id)?.setStyle(roadStyle(match.road));updateProgress()}}$('distance').textContent=(state.distanceKm*.621371).toFixed(2);$('point-count').textContent=state.pointCount;$('new-roads').textContent=state.newRoads.size}
function toggleDrive(){state.tracking?stopDrive():startDrive()}
function startDrive(){startLocationWatch();state.tracking=true;state.lastPoint=null;state.distanceKm=0;state.pointCount=0;state.newRoads.clear();$('drive-state').textContent='Tracking';$('drive-button').textContent='Stop drive';$('drive-button').classList.add('stop');$('new-roads').textContent='0';$('point-count').textContent='0';$('distance').textContent='0.00';toast('Drive started — GPS tracking is live')}
function stopDrive(){state.tracking=false;const journey={date:new Date().toISOString(),mode:state.mode,miles:Number((state.distanceKm*.621371).toFixed(2)),newRoads:state.newRoads.size,points:state.pointCount};if(journey.points)state.journeys.unshift(journey);state.journeys=state.journeys.slice(0,30);save(STORE.journeys,state.journeys);$('drive-state').textContent='Complete';$('drive-button').textContent='Start drive';$('drive-button').classList.remove('stop');renderJourneys();toast(`Drive saved · ${journey.miles.toFixed(2)} miles`)}
function updateProgress(){const pct=state.roads.length?100*state.roads.filter(r=>state.completed.has(String(r.id))).length/state.roads.length:0;const text=pct.toFixed(1)+'%';$('completion').textContent=text;$('progress-completion').textContent=text;$('progress-fill').style.width=Math.min(100,pct)+'%';$('segment-count').textContent=state.roads.length?state.roads.length.toLocaleString():'—'}
function renderJourneys(){$('journey-list').innerHTML=state.journeys.length?state.journeys.map(j=>`<article class="journey"><div><p>${j.mode==='bike'?'Bike':'Car'} journey</p><small>${new Date(j.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})} · ${j.newRoads} new roads</small></div><strong>${Number(j.miles).toFixed(2)} mi</strong></article>`).join(''):'<p class="empty">No journeys recorded yet.</p>'}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='map-view')setTimeout(()=>state.map.invalidateSize(),30);if(id==='progress-view')renderJourneys()}
document.querySelectorAll('.nav-button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
document.querySelectorAll('.mode').forEach(b=>{b.classList.toggle('active',b.dataset.mode===state.mode);b.addEventListener('click',()=>{state.mode=b.dataset.mode;localStorage.setItem(STORE.mode,state.mode);document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b))})});
$('locate-button').addEventListener('click',()=>{startLocationWatch();if(state.userMarker)state.map.setView(state.userMarker.getLatLng(),17);else toast('Finding your location…')});$('drive-button').addEventListener('click',toggleDrive);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
initMap();renderJourneys();updateProgress();
